# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: GererateProfile

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      
      - name: Generate Snake
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          gif_out_path: ./snakes/github-contribution-grid-snake.gif
          svg_out_path: ./snakes/github-contribution-grid-snake.svg
          
      - name: GitHub-Profile-3D-Contrib
        uses: yoshi389111/github-profile-3d-contrib@0.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config user.name dukechain2333
          git config user.email qianzehao1113@icloud.com
          git add -A .
          git commit -m "generated"
          git push
